/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran_otomasyon;

import static restoran_otomasyon.satis_panel.uadi;
import static restoran_otomasyon.satis_panel.ufiyati;
import static restoran_otomasyon.satis_panel.uid;
import java.awt.ComponentOrientation;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Samet
 */
public class admin_panel extends javax.swing.JFrame {

    static Connection con;
    static String fullurl = "jdbc:sqlserver://localhost:1433;databasename=gorsel3;user=sa;password=1";
    static String k_adi;
    static String k_sifre;
    static String queryHasilat;

    /**
     * Creates new form admin_panel
     */
    public admin_panel() throws SQLException {
        initComponents();
        urunGoster();
        yoneticiGoster();
        display_masalar();
    }

    //Burada database'den ürünler çekilip tabloya yazdırıldı.
    public static void urunGoster() throws SQLException {
        final String QUERY = "Select urun_id, urun_adi, urun_fiyati from urunler";
        con = DriverManager.getConnection(fullurl);
        System.out.println("Bağlantı Kuruldu");
        java.sql.Statement stmt = con.createStatement();
        DefaultTableModel model = (DefaultTableModel) display_urunler2.getModel();
        ResultSet rs = stmt.executeQuery(QUERY);
        int i = 0;
        while (rs.next()) {
            uid = rs.getString("urun_id");
            uadi = rs.getString("urun_adi");
            ufiyati = rs.getString("urun_fiyati");
            model.addRow(new Object[]{uid, uadi, ufiyati});
            i++;
        }
    }

    //databasedeki masalar çekilerek tabloya yazdırıldı.
    public static void display_masalar() throws SQLException {
        final String QUERY = "Select * from masa";
        con = DriverManager.getConnection(fullurl);
        java.sql.Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(QUERY);
        DefaultTableModel model2 = (DefaultTableModel) masalar_display.getModel();
        String masalar = null;
        while (rs.next()) {
            masalar = rs.getString("masa");
            model2.addRow(new Object[]{masalar});
        }
    }

    //databasedeki yöneticiler tabloya yazdırıldı.
    public static void yoneticiGoster() throws SQLException {
        final String QUERY = "Select admin_kullanici_adi, admin_sifre from adminler";
        con = DriverManager.getConnection(fullurl);
        System.out.println("Bağlantı Kuruldu");
        java.sql.Statement stmt = con.createStatement();
        DefaultTableModel model = (DefaultTableModel) yonetici_table.getModel();
        ResultSet rs = stmt.executeQuery(QUERY);
        int i = 0;
        while (rs.next()) {
            k_adi = rs.getString("admin_kullanici_adi");
            k_sifre = rs.getString("admin_sifre");
            model.addRow(new Object[]{k_adi, k_sifre});
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        masa_adi_gir = new javax.swing.JTextField();
        masa_ekle = new javax.swing.JButton();
        masa_cikar_adi_input = new javax.swing.JTextField();
        masa_cikar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        masalar_display = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        sifre_girilen = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        kullanici_adi_girilen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yonetici_ekle_button = new javax.swing.JButton();
        yonetici_cikar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kullanici_adi_girilen1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        display_urunler2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        gunSecBas = new javax.swing.JComboBox<>();
        aySecBas = new javax.swing.JComboBox<>();
        yilSecBas = new javax.swing.JComboBox<>();
        yilSecSon = new javax.swing.JComboBox<>();
        aySecSon = new javax.swing.JComboBox<>();
        gunSecSon = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        raporGoruntule = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        yonetici_table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        urunEkle_id = new javax.swing.JTextField();
        urunEkle_adi = new javax.swing.JTextField();
        urunEkle_fiyati = new javax.swing.JTextField();
        urun_ekle_button = new javax.swing.JButton();
        ürün_cikar = new javax.swing.JButton();
        ürün_id_cikar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setExtendedState(MAXIMIZED_BOTH);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Masa Ekle");

        masa_adi_gir.setText("Masa Adı");
        masa_adi_gir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_adi_girActionPerformed(evt);
            }
        });

        masa_ekle.setText("Ekle");
        masa_ekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa_ekleMouseClicked(evt);
            }
        });
        masa_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_ekleActionPerformed(evt);
            }
        });

        masa_cikar_adi_input.setText("Masa Adı");
        masa_cikar_adi_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_cikar_adi_inputActionPerformed(evt);
            }
        });

        masa_cikar.setText("Çıkar");
        masa_cikar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa_cikarMouseClicked(evt);
            }
        });
        masa_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_cikarActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Masa Çıkar");

        masalar_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Masalar"
            }
        ));
        jScrollPane3.setViewportView(masalar_display);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(masa_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(masa_adi_gir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(masa_cikar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(masa_cikar_adi_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(masa_adi_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masa_ekle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(masa_cikar_adi_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masa_cikar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Şifre:");

        kullanici_adi_girilen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_adi_girilenActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Yönetici Ekle");

        yonetici_ekle_button.setText("Ekle");
        yonetici_ekle_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yonetici_ekle_buttonMouseClicked(evt);
            }
        });
        yonetici_ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yonetici_ekle_buttonActionPerformed(evt);
            }
        });

        yonetici_cikar.setText("Çıkar");
        yonetici_cikar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yonetici_cikarMouseClicked(evt);
            }
        });
        yonetici_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yonetici_cikarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Kullanıcı Adı:");

        kullanici_adi_girilen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_adi_girilen1ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Yönetici Çıkar");

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Kullanıcı Adı:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kullanici_adi_girilen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yonetici_ekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sifre_girilen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kullanici_adi_girilen1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yonetici_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kullanici_adi_girilen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sifre_girilen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yonetici_ekle_button)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanici_adi_girilen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addComponent(yonetici_cikar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Kayıtlı Ürünler");

        display_urunler2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "fiyat"
            }
        ));
        jScrollPane2.setViewportView(display_urunler2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Hasılat Raporu Çıkar");

        gunSecBas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        gunSecBas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gunSecBasMouseClicked(evt);
            }
        });
        gunSecBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gunSecBasActionPerformed(evt);
            }
        });

        aySecBas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        yilSecBas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017" }));

        yilSecSon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017" }));

        aySecSon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        gunSecSon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Başlangıç Tarihi");

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Bitiş Tarihi");

        raporGoruntule.setText("Raporu Göster");
        raporGoruntule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raporGoruntuleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addComponent(raporGoruntule)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gunSecBas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gunSecSon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(aySecSon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yilSecSon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(aySecBas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yilSecBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gunSecBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aySecBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yilSecBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yilSecSon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aySecSon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gunSecSon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(raporGoruntule)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        yonetici_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanici Adi", "Sifre"
            }
        ));
        jScrollPane1.setViewportView(yonetici_table);

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Kayıtlı Yöneticiler");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Ürün Ekle");

        urunEkle_id.setText("Ürün ID");

        urunEkle_adi.setText("Ürün Adı");

        urunEkle_fiyati.setText("Ürün Fiyatı");

        urun_ekle_button.setText("Ekle");
        urun_ekle_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_ekle_buttonMouseClicked(evt);
            }
        });
        urun_ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_ekle_buttonActionPerformed(evt);
            }
        });

        ürün_cikar.setText("Çıkar");
        ürün_cikar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ürün_cikarMouseClicked(evt);
            }
        });
        ürün_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürün_cikarActionPerformed(evt);
            }
        });

        ürün_id_cikar.setText("Ürün ID");
        ürün_id_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürün_id_cikarActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Ürün Çıkar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(urunEkle_id)
                        .addComponent(urunEkle_adi)
                        .addComponent(urun_ekle_button)
                        .addComponent(urunEkle_fiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(ürün_id_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ürün_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(urunEkle_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(urunEkle_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(urunEkle_fiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(urun_ekle_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ürün_id_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ürün_cikar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullanici_adi_girilenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_adi_girilenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullanici_adi_girilenActionPerformed

    private void yonetici_ekle_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yonetici_ekle_buttonMouseClicked
        try {
            String ad = "";
            String sifre = "";
            ad = kullanici_adi_girilen.getText().trim();
            sifre = sifre_girilen.getText().trim();
            String query = "insert into dbo.adminler (admin_kullanici_adi, admin_sifre) values('" + ad + "', '" + sifre + "')";
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) yonetici_table.getModel();
            model.setRowCount(0);
            yoneticiGoster();
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yonetici_ekle_buttonMouseClicked

    private void yonetici_ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yonetici_ekle_buttonActionPerformed

    }//GEN-LAST:event_yonetici_ekle_buttonActionPerformed

    private void yonetici_cikarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yonetici_cikarMouseClicked
        try {
            String ad = null;
            ad = kullanici_adi_girilen1.getText();
            String query = "delete from adminler where admin_kullanici_adi='" + ad + "'";
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) yonetici_table.getModel();
            model.setRowCount(0);
            yoneticiGoster();
            kullanici_adi_girilen1.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yonetici_cikarMouseClicked

    private void yonetici_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yonetici_cikarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yonetici_cikarActionPerformed

    private void kullanici_adi_girilen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_adi_girilen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullanici_adi_girilen1ActionPerformed

    private void urun_ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_ekle_buttonActionPerformed
        try {
            ResultSet rs;
            String urun_idx = "";
            String urun_adix = "";
            String urun_fiyatix = "";
            urun_idx = urunEkle_id.getText().trim();
            urun_adix = urunEkle_adi.getText().trim();
            urun_fiyatix = urunEkle_fiyati.getText().trim();
            String query = "insert into dbo.urunler (urun_id, urun_adi, urun_fiyati) values('" + urun_idx + "', '" + urun_adix + "', '" + urun_fiyatix + "')";
            con = DriverManager.getConnection(fullurl);
            java.sql.Statement stmt = con.createStatement();
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) display_urunler2.getModel();
            model.setRowCount(0);
            urunGoster();
            urunEkle_id.setText("");
            urunEkle_adi.setText("");
            urunEkle_fiyati.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_urun_ekle_buttonActionPerformed

    private void urun_ekle_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_ekle_buttonMouseClicked

    }//GEN-LAST:event_urun_ekle_buttonMouseClicked

    private void ürün_cikarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ürün_cikarMouseClicked
        try {
            String id = null;
            id = ürün_id_cikar.getText();
            String query = "delete from urunler where urun_id='" + id + "'";
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) display_urunler2.getModel();
            model.setRowCount(0);
            urunGoster();
            ürün_id_cikar.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ürün_cikarMouseClicked

    private void ürün_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürün_cikarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ürün_cikarActionPerformed

    private void ürün_id_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürün_id_cikarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ürün_id_cikarActionPerformed

    private void masa_adi_girActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_adi_girActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa_adi_girActionPerformed

    private void masa_ekleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa_ekleMouseClicked
        try {
            String id = "";
            id = masa_adi_gir.getText().trim();
            String query = "insert into dbo.masa (masa) values('" + id + "')";
            con = DriverManager.getConnection(fullurl);
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) masalar_display.getModel();
            model.setRowCount(0);
            display_masalar();
            masa_adi_gir.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_masa_ekleMouseClicked

    private void masa_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_ekleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa_ekleActionPerformed

    private void masa_cikar_adi_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_cikar_adi_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa_cikar_adi_inputActionPerformed

    private void masa_cikarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa_cikarMouseClicked
        try {
            String id = null;
            id = masa_cikar_adi_input.getText();
            String query = "delete from masa where masa='" + id + "'";
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) masalar_display.getModel();
            model.setRowCount(0);
            display_masalar();
            masa_cikar_adi_input.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_masa_cikarMouseClicked

    private void masa_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_cikarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa_cikarActionPerformed

    private void gunSecBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunSecBasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gunSecBasActionPerformed

    private void gunSecBasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gunSecBasMouseClicked

    }//GEN-LAST:event_gunSecBasMouseClicked

    private void raporGoruntuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raporGoruntuleMouseClicked
        try {
            gunSecBas.getSelectedItem();
            aySecBas.getSelectedItem();
            yilSecBas.getSelectedItem();
            gunSecSon.getSelectedItem();
            aySecSon.getSelectedItem();
            yilSecSon.getSelectedItem();
            System.out.println(" " + gunSecBas.getSelectedItem()
                    + aySecBas.getSelectedItem()
                    + yilSecBas.getSelectedItem()
                    + gunSecSon.getSelectedItem()
                    + aySecSon.getSelectedItem()
                    + yilSecSon.getSelectedItem());
            String baslangicTarihi = "" + yilSecBas.getSelectedItem() + "-" + aySecBas.getSelectedItem() + "-" + gunSecBas.getSelectedItem();
            String bitisTarihi = "" + yilSecSon.getSelectedItem() + "-" + aySecSon.getSelectedItem() + "-" + gunSecSon.getSelectedItem();
            System.out.println(baslangicTarihi);
            System.out.println(bitisTarihi);
            queryHasilat = "select * from siparisler where Tarih between '" + baslangicTarihi + "' and '" + bitisTarihi + "'";
            hasilat_raporu hasilatRapru = new hasilat_raporu();
            //hasilat_raporu.show();
            hasilatRapru.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_raporGoruntuleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new admin_panel().setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> aySecBas;
    private static javax.swing.JComboBox<String> aySecSon;
    private static javax.swing.JTable display_urunler2;
    private static javax.swing.JComboBox<String> gunSecBas;
    private static javax.swing.JComboBox<String> gunSecSon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    static javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kullanici_adi_girilen;
    private javax.swing.JTextField kullanici_adi_girilen1;
    private javax.swing.JTextField masa_adi_gir;
    private javax.swing.JButton masa_cikar;
    private javax.swing.JTextField masa_cikar_adi_input;
    private javax.swing.JButton masa_ekle;
    private static javax.swing.JTable masalar_display;
    private javax.swing.JButton raporGoruntule;
    private javax.swing.JPasswordField sifre_girilen;
    private javax.swing.JTextField urunEkle_adi;
    private javax.swing.JTextField urunEkle_fiyati;
    private javax.swing.JTextField urunEkle_id;
    private javax.swing.JButton urun_ekle_button;
    private static javax.swing.JComboBox<String> yilSecBas;
    private static javax.swing.JComboBox<String> yilSecSon;
    private javax.swing.JButton yonetici_cikar;
    private javax.swing.JButton yonetici_ekle_button;
    private static javax.swing.JTable yonetici_table;
    private javax.swing.JButton ürün_cikar;
    private javax.swing.JTextField ürün_id_cikar;
    // End of variables declaration//GEN-END:variables
}
