/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran_otomasyon;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.sql.ResultSet;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samet
 */
public class admin_panel extends javax.swing.JFrame {

    static Connection con;
    static String fullurl = "jdbc:sqlserver://localhost:1433;databasename=gorsel3;user=sa;password=1";
    static String k_adi;
    static String k_sifre;
    static String queryHasilat;
    static String uid = "";
    static String uadi = "";
    static String ufiyati = "";
    static int toplamTutar = 0;
    static String tutar = "";

    /*static int toplamTutar = 0;
    static int tutar = 0;*/

    /**
     * Creates new form admin_panel
     */
    public admin_panel() {
        initComponents();
        try {
            urunGoster();
            yoneticiGoster();
            display_masalar();
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Urunler_Panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        urunEkle_id = new javax.swing.JTextField();
        urunEkle_adi = new javax.swing.JTextField();
        urunEkle_fiyati = new javax.swing.JTextField();
        urun_ekle_button = new javax.swing.JButton();
        ürün_cikar = new javax.swing.JButton();
        ürün_id_cikar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        display_urunler = new javax.swing.JTable();
        Yoneticiler_Panel = new javax.swing.JPanel();
        sifre_girilen = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        kullanici_adi_girilen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yonetici_ekle_button = new javax.swing.JButton();
        yonetici_cikar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kullanici_adi_girilen1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        yonetici_table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Masalar_Panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        masa_adi_gir = new javax.swing.JTextField();
        masa_ekle = new javax.swing.JButton();
        masa_cikar_adi_input = new javax.swing.JTextField();
        masa_cikar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        masalar_display = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Hasilat_Raporlari = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        gunSecBas = new javax.swing.JComboBox<>();
        aySecBas = new javax.swing.JComboBox<>();
        yilSecBas = new javax.swing.JComboBox<>();
        yilSecSon = new javax.swing.JComboBox<>();
        aySecSon = new javax.swing.JComboBox<>();
        gunSecSon = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        raporGoruntule = new javax.swing.JButton();
        hasilatRaporuTable = new javax.swing.JScrollPane();
        raporTablo = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        toplamTutarGoster = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setExtendedState(MAXIMIZED_BOTH);

        Urunler_Panel.setBackground(new java.awt.Color(51, 51, 51));
        Urunler_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Ürün Ekle");

        urunEkle_fiyati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunEkle_fiyatiActionPerformed(evt);
            }
        });

        urun_ekle_button.setText("Ekle");
        urun_ekle_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_ekle_buttonMouseClicked(evt);
            }
        });
        urun_ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_ekle_buttonActionPerformed(evt);
            }
        });

        ürün_cikar.setText("Çıkar");
        ürün_cikar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ürün_cikarMouseClicked(evt);
            }
        });
        ürün_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürün_cikarActionPerformed(evt);
            }
        });

        ürün_id_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürün_id_cikarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Ürün Çıkar");

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Ürün ID: ");

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Ürün Adı:");

        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Ürün Fiyatı:");

        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Ürün ID: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Kayıtlı Ürünler");

        display_urunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "urun_id", "urun_adi", "urun_fiyati"
            }
        ));
        jScrollPane4.setViewportView(display_urunler);

        javax.swing.GroupLayout Urunler_PanelLayout = new javax.swing.GroupLayout(Urunler_Panel);
        Urunler_Panel.setLayout(Urunler_PanelLayout);
        Urunler_PanelLayout.setHorizontalGroup(
            Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Urunler_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(Urunler_PanelLayout.createSequentialGroup()
                        .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel11)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(urunEkle_id)
                            .addComponent(urunEkle_fiyati)
                            .addComponent(urunEkle_adi)
                            .addComponent(urun_ekle_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ürün_id_cikar)
                            .addComponent(ürün_cikar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))))
                .addGap(47, 47, 47)
                .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        Urunler_PanelLayout.setVerticalGroup(
            Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Urunler_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Urunler_PanelLayout.createSequentialGroup()
                        .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urunEkle_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urunEkle_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urunEkle_fiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(urun_ekle_button)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Urunler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(ürün_id_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ürün_cikar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ürünler", Urunler_Panel);

        Yoneticiler_Panel.setBackground(new java.awt.Color(51, 51, 51));
        Yoneticiler_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Yoneticiler_Panel.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Şifre:");

        kullanici_adi_girilen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_adi_girilenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Yönetici Ekle");

        yonetici_ekle_button.setText("Ekle");
        yonetici_ekle_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yonetici_ekle_buttonMouseClicked(evt);
            }
        });
        yonetici_ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yonetici_ekle_buttonActionPerformed(evt);
            }
        });

        yonetici_cikar.setText("Çıkar");
        yonetici_cikar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yonetici_cikarMouseClicked(evt);
            }
        });
        yonetici_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yonetici_cikarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Kullanıcı Adı:");

        kullanici_adi_girilen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_adi_girilen1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Yönetici Çıkar");

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Kullanıcı Adı:");

        yonetici_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanici Adi", "Sifre"
            }
        ));
        jScrollPane1.setViewportView(yonetici_table);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Kayıtlı Yöneticiler");

        javax.swing.GroupLayout Yoneticiler_PanelLayout = new javax.swing.GroupLayout(Yoneticiler_Panel);
        Yoneticiler_Panel.setLayout(Yoneticiler_PanelLayout);
        Yoneticiler_PanelLayout.setHorizontalGroup(
            Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Yoneticiler_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addGroup(Yoneticiler_PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kullanici_adi_girilen1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yonetici_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Yoneticiler_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kullanici_adi_girilen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(Yoneticiler_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yonetici_ekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifre_girilen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Yoneticiler_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addContainerGap())
        );
        Yoneticiler_PanelLayout.setVerticalGroup(
            Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Yoneticiler_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Yoneticiler_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(kullanici_adi_girilen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sifre_girilen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yonetici_ekle_button)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Yoneticiler_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullanici_adi_girilen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addComponent(yonetici_cikar))
                    .addGroup(Yoneticiler_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Yöneticiler", Yoneticiler_Panel);

        Masalar_Panel.setBackground(new java.awt.Color(51, 51, 51));
        Masalar_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Masa Ekle");

        masa_adi_gir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_adi_girActionPerformed(evt);
            }
        });

        masa_ekle.setText("Ekle");
        masa_ekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa_ekleMouseClicked(evt);
            }
        });
        masa_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_ekleActionPerformed(evt);
            }
        });

        masa_cikar_adi_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_cikar_adi_inputActionPerformed(evt);
            }
        });

        masa_cikar.setText("Çıkar");
        masa_cikar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa_cikarMouseClicked(evt);
            }
        });
        masa_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_cikarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Masa Çıkar");

        masalar_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Masalar"
            }
        ));
        jScrollPane3.setViewportView(masalar_display);

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Masa Adı:");

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Masa Adı:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Kayıtlı Masalar");

        javax.swing.GroupLayout Masalar_PanelLayout = new javax.swing.GroupLayout(Masalar_Panel);
        Masalar_Panel.setLayout(Masalar_PanelLayout);
        Masalar_PanelLayout.setHorizontalGroup(
            Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Masalar_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Masalar_PanelLayout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(masa_adi_gir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Masalar_PanelLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(masa_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Masalar_PanelLayout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(masa_cikar_adi_input, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Masalar_PanelLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(masa_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(Masalar_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Masalar_PanelLayout.setVerticalGroup(
            Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Masalar_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel21))
                .addGap(6, 6, 6)
                .addGroup(Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Masalar_PanelLayout.createSequentialGroup()
                        .addGroup(Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masa_adi_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masa_ekle)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addGroup(Masalar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masa_cikar_adi_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masa_cikar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Masalar", Masalar_Panel);

        Hasilat_Raporlari.setBackground(new java.awt.Color(51, 51, 51));
        Hasilat_Raporlari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Hasılat Raporu Çıkar");

        gunSecBas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        gunSecBas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gunSecBasMouseClicked(evt);
            }
        });
        gunSecBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gunSecBasActionPerformed(evt);
            }
        });

        aySecBas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        yilSecBas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017" }));

        yilSecSon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017" }));

        aySecSon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        gunSecSon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Başlangıç Tarihi (Gün-Ay-Yıl)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Bitiş Tarihi (Gün-Ay-Yıl)");

        raporGoruntule.setText("Raporu Göster");
        raporGoruntule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raporGoruntuleMouseClicked(evt);
            }
        });

        raporTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sipariş ID", "Tarih", "Tutar"
            }
        ));
        hasilatRaporuTable.setViewportView(raporTablo);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Hasılat Raporu");

        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Toplam Tutar:");

        javax.swing.GroupLayout Hasilat_RaporlariLayout = new javax.swing.GroupLayout(Hasilat_Raporlari);
        Hasilat_Raporlari.setLayout(Hasilat_RaporlariLayout);
        Hasilat_RaporlariLayout.setHorizontalGroup(
            Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hasilat_RaporlariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Hasilat_RaporlariLayout.createSequentialGroup()
                        .addGroup(Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(Hasilat_RaporlariLayout.createSequentialGroup()
                                .addComponent(gunSecBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aySecBas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yilSecBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(raporGoruntule)
                            .addGroup(Hasilat_RaporlariLayout.createSequentialGroup()
                                .addComponent(gunSecSon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aySecSon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yilSecSon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasilatRaporuTable, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hasilat_RaporlariLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toplamTutarGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Hasilat_RaporlariLayout.setVerticalGroup(
            Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hasilat_RaporlariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addGroup(Hasilat_RaporlariLayout.createSequentialGroup()
                        .addGroup(Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Hasilat_RaporlariLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gunSecBas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(aySecBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yilSecBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gunSecSon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hasilat_RaporlariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(yilSecSon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aySecSon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(raporGoruntule))
                            .addGroup(Hasilat_RaporlariLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(hasilatRaporuTable, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toplamTutarGoster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hasılat Raporu", Hasilat_Raporlari);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullanici_adi_girilenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_adi_girilenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullanici_adi_girilenActionPerformed

    private void yonetici_ekle_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yonetici_ekle_buttonMouseClicked
        try {
            String ad = "";
            String sifre = "";
            ad = kullanici_adi_girilen.getText().trim();
            sifre = sifre_girilen.getText().trim();
            String query = "insert into dbo.adminler (admin_kullanici_adi, admin_sifre) values('" + ad + "', '" + sifre + "')";
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) yonetici_table.getModel();
            model.setRowCount(0);
            yoneticiGoster();
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yonetici_ekle_buttonMouseClicked

    private void yonetici_ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yonetici_ekle_buttonActionPerformed

    }//GEN-LAST:event_yonetici_ekle_buttonActionPerformed

    private void yonetici_cikarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yonetici_cikarMouseClicked
        try {
            String ad = null;
            ad = kullanici_adi_girilen1.getText();
            String query = "delete from adminler where admin_kullanici_adi='" + ad + "'";
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) yonetici_table.getModel();
            model.setRowCount(0);
            yoneticiGoster();
            kullanici_adi_girilen1.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yonetici_cikarMouseClicked

    private void yonetici_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yonetici_cikarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yonetici_cikarActionPerformed

    private void kullanici_adi_girilen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_adi_girilen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullanici_adi_girilen1ActionPerformed

    private void urun_ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_ekle_buttonActionPerformed
        try {
            ResultSet rs;
            String urun_idx = "";
            String urun_adix = "";
            String urun_fiyatix = "";
            urun_idx = urunEkle_id.getText().trim();
            urun_adix = urunEkle_adi.getText().trim();
            urun_fiyatix = urunEkle_fiyati.getText().trim();
            String query = "insert into dbo.urunler (urun_id, urun_adi, urun_fiyati) values('" + urun_idx + "', '" + urun_adix + "', '" + urun_fiyatix + "')";
            con = DriverManager.getConnection(fullurl);
            java.sql.Statement stmt = con.createStatement();
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) display_urunler.getModel();
            model.setRowCount(0);
            urunGoster();
            urunEkle_id.setText("");
            urunEkle_adi.setText("");
            urunEkle_fiyati.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_urun_ekle_buttonActionPerformed

    private void urun_ekle_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_ekle_buttonMouseClicked

    }//GEN-LAST:event_urun_ekle_buttonMouseClicked

    private void ürün_cikarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ürün_cikarMouseClicked
        try {
            String id = null;
            id = ürün_id_cikar.getText();
            String query = "delete from urunler where urun_id='" + id + "'";
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) display_urunler.getModel();
            model.setRowCount(0);
            urunGoster();
            ürün_id_cikar.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ürün_cikarMouseClicked

    private void ürün_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürün_cikarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ürün_cikarActionPerformed

    private void ürün_id_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürün_id_cikarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ürün_id_cikarActionPerformed

    private void masa_adi_girActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_adi_girActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa_adi_girActionPerformed

    private void masa_ekleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa_ekleMouseClicked
        try {
            String id = "";
            id = masa_adi_gir.getText().trim();
            String query = "insert into dbo.masa (masa) values('" + id + "')";
            con = DriverManager.getConnection(fullurl);
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) masalar_display.getModel();
            model.setRowCount(0);
            display_masalar();
            masa_adi_gir.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_masa_ekleMouseClicked

    private void masa_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_ekleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa_ekleActionPerformed

    private void masa_cikar_adi_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_cikar_adi_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa_cikar_adi_inputActionPerformed

    private void masa_cikarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa_cikarMouseClicked
        try {
            String id = null;
            id = masa_cikar_adi_input.getText();
            String query = "delete from masa where masa='" + id + "'";
            ((Connection) con).createStatement().execute(query);
            DefaultTableModel model = (DefaultTableModel) masalar_display.getModel();
            model.setRowCount(0);
            display_masalar();
            masa_cikar_adi_input.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_masa_cikarMouseClicked

    private void masa_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_cikarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa_cikarActionPerformed

    private void gunSecBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunSecBasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gunSecBasActionPerformed

    private void gunSecBasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gunSecBasMouseClicked

    }//GEN-LAST:event_gunSecBasMouseClicked

    private void raporGoruntuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raporGoruntuleMouseClicked
        try {
            gunSecBas.getSelectedItem();
            aySecBas.getSelectedItem();
            yilSecBas.getSelectedItem();
            gunSecSon.getSelectedItem();
            aySecSon.getSelectedItem();
            yilSecSon.getSelectedItem();
            System.out.println(" " + gunSecBas.getSelectedItem()
                    + aySecBas.getSelectedItem()
                    + yilSecBas.getSelectedItem()
                    + gunSecSon.getSelectedItem()
                    + aySecSon.getSelectedItem()
                    + yilSecSon.getSelectedItem());
            String baslangicTarihi = "" + yilSecBas.getSelectedItem() + "-" + aySecBas.getSelectedItem() + "-" + gunSecBas.getSelectedItem();
            String bitisTarihi = "" + yilSecSon.getSelectedItem() + "-" + aySecSon.getSelectedItem() + "-" + gunSecSon.getSelectedItem();
            System.out.println(baslangicTarihi);
            System.out.println(bitisTarihi);
            queryHasilat = "select * from siparisler where Tarih between '" + baslangicTarihi + "' and '" + bitisTarihi + "'";
            //hasilat_raporu hasilatRapru = new hasilat_raporu();
            //hasilat_raporu.show();
            //hasilatRapru.setVisible(true);
            raporGoster();
            toplamTutarHesapla();
        } catch (SQLException ex) {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_raporGoruntuleMouseClicked

    private void urunEkle_fiyatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunEkle_fiyatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunEkle_fiyatiActionPerformed

    public static void raporGoster() throws SQLException {
        con = DriverManager.getConnection(fullurl);
        System.out.println("Bağlantı Kuruldu");
        System.out.println("asadasdasd" + queryHasilat);
        java.sql.Statement stmt = con.createStatement();
        DefaultTableModel model = (DefaultTableModel) raporTablo.getModel();
        ResultSet rs = stmt.executeQuery(queryHasilat);
        int i = 0;
        while (rs.next()) {
            String sid = rs.getString("siparis_ID");
            String tarih = rs.getString("Tarih");
            String tutar = rs.getString("Toplam_fiyat");
            System.out.println(sid + tarih + tutar);
            model.addRow(new Object[]{sid, tarih, tutar});
            i++;
        }
    }

    //Burada database'den ürünler çekilip tabloya yazdırıldı.
    void urunGoster() throws SQLException {
        final String QUERY = "Select urun_id, urun_adi, urun_fiyati from urunler";
        con = DriverManager.getConnection(fullurl);
        System.out.println("Bağlantı Kuruldu");
        java.sql.Statement stmt = con.createStatement();
        DefaultTableModel model = (DefaultTableModel) display_urunler.getModel();
        ResultSet rs = stmt.executeQuery(QUERY);
        int i = 0;
        while (rs.next()) {
            uid = rs.getString("urun_id");
            uadi = rs.getString("urun_adi");
            ufiyati = rs.getString("urun_fiyati");
            model.addRow(new Object[]{uid, uadi, ufiyati});
            i++;
        }
    }

    //databasedeki masalar çekilerek tabloya yazdırıldı.
    public static void display_masalar() throws SQLException {
        final String QUERY = "Select * from masa";
        con = DriverManager.getConnection(fullurl);
        java.sql.Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(QUERY);
        DefaultTableModel model2 = (DefaultTableModel) masalar_display.getModel();
        String masalar = null;
        while (rs.next()) {
            masalar = rs.getString("masa");
            model2.addRow(new Object[]{masalar});
        }
    }

    //databasedeki yöneticiler tabloya yazdırıldı.
    public static void yoneticiGoster() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) yonetici_table.getModel();
        final String QUERY = "Select admin_kullanici_adi, admin_sifre from adminler";
        con = DriverManager.getConnection(fullurl);
        System.out.println("Bağlantı Kuruldu");
        java.sql.Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(QUERY);
        int i = 0;
        while (rs.next()) {
            k_adi = rs.getString("admin_kullanici_adi");
            k_sifre = rs.getString("admin_sifre");
            model.addRow(new Object[]{k_adi, k_sifre});
            i++;
        }
    }

    static void toplamTutarHesapla() {
        DefaultTableModel model = (DefaultTableModel) raporTablo.getModel();
        int satirSayisi = model.getRowCount();
        System.out.println("toplam tutar hesapla: Toplam Tutar: " + toplamTutar + "toplam tutar2: " + String.valueOf(toplamTutar) + "satır sayısı " + satirSayisi);
        System.out.println("model get value: " + model.getValueAt(1, 2));
        for (int i = 0; i < satirSayisi; i++) {
            tutar = (String) model.getValueAt(i, 2);
            toplamTutar = toplamTutar + Integer.parseInt(tutar);
        }
        toplamTutarGoster.setText(String.valueOf(toplamTutar));

        System.out.println("toplam tutar hesapla: Toplam Tutar: " + toplamTutar + "toplam tutar2: " + String.valueOf(toplamTutar) + "satır sayısı " + satirSayisi);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new admin_panel().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JPanel Hasilat_Raporlari;
    private javax.swing.JPanel Masalar_Panel;
    private static javax.swing.JPanel Urunler_Panel;
    private javax.swing.JPanel Yoneticiler_Panel;
    private static javax.swing.JComboBox<String> aySecBas;
    private static javax.swing.JComboBox<String> aySecSon;
    private static javax.swing.JTable display_urunler;
    private static javax.swing.JComboBox<String> gunSecBas;
    private static javax.swing.JComboBox<String> gunSecSon;
    private javax.swing.JScrollPane hasilatRaporuTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kullanici_adi_girilen;
    private javax.swing.JTextField kullanici_adi_girilen1;
    private javax.swing.JTextField masa_adi_gir;
    private javax.swing.JButton masa_cikar;
    private javax.swing.JTextField masa_cikar_adi_input;
    private javax.swing.JButton masa_ekle;
    private static javax.swing.JTable masalar_display;
    private javax.swing.JButton raporGoruntule;
    private static javax.swing.JTable raporTablo;
    private javax.swing.JPasswordField sifre_girilen;
    private static javax.swing.JTextField toplamTutarGoster;
    private javax.swing.JTextField urunEkle_adi;
    private javax.swing.JTextField urunEkle_fiyati;
    private javax.swing.JTextField urunEkle_id;
    private javax.swing.JButton urun_ekle_button;
    private static javax.swing.JComboBox<String> yilSecBas;
    private static javax.swing.JComboBox<String> yilSecSon;
    private javax.swing.JButton yonetici_cikar;
    private javax.swing.JButton yonetici_ekle_button;
    private static javax.swing.JTable yonetici_table;
    private javax.swing.JButton ürün_cikar;
    private javax.swing.JTextField ürün_id_cikar;
    // End of variables declaration//GEN-END:variables
}
